"""Route generation script for NeuroTraffic-RL.

Generates or regenerates ``casablanca_intersection.rou.xml`` from
demand parameters.  Useful for quick experimentation with different
traffic scenarios without hand-editing XML.

Usage::

    python sumo/tools/generate_routes.py
    python sumo/tools/generate_routes.py --output sumo/networks/custom.rou.xml \\
        --ns-peak 1000 --ew-peak 700
"""

from __future__ import annotations

import argparse
from pathlib import Path
from textwrap import dedent


_DEFAULT_OUTPUT = Path(__file__).parent.parent / "networks" / "casablanca_intersection.rou.xml"


def generate_routes(
    output: Path,
    ns_peak: int = 800,
    ew_peak: int = 600,
    ns_offpeak: int = 300,
    ew_offpeak: int = 200,
    sim_end: int = 3600,
) -> None:
    """Generate a SUMO route file with parameterised demand.

    Args:
        output:      Path to write the ``.rou.xml`` file.
        ns_peak:     Total peak NS demand (veh/hr, split equally N→S and S→N).
        ew_peak:     Total peak EW demand (veh/hr).
        ns_offpeak:  Total off-peak NS demand (veh/hr).
        ew_offpeak:  Total off-peak EW demand (veh/hr).
        sim_end:     Simulation end time (seconds). Default 3600 (1 hour).
    """
    # For a 1-hour sim: use all as morning rush
    ns_each = ns_peak // 2
    ew_each = ew_peak // 2
    ns_off = ns_offpeak // 2
    ew_off = ew_offpeak // 2

    content = dedent(f"""\
        <?xml version="1.0" encoding="UTF-8"?>
        <!-- Generated by sumo/tools/generate_routes.py
             NS peak: {ns_peak} veh/hr  EW peak: {ew_peak} veh/hr -->
        <routes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/routes_file.xsd">

            <vType id="car" accel="2.6" decel="4.5" sigma="0.5" length="5.0"
                   minGap="2.5" maxSpeed="13.89" guiShape="passenger"/>

            <!-- Through routes -->
            <route id="NS" edges="N2J J2S"/>
            <route id="SN" edges="S2J J2N"/>
            <route id="EW" edges="E2J J2W"/>
            <route id="WE" edges="W2J J2E"/>
            <!-- Turning routes -->
            <route id="NE" edges="N2J J2E"/>
            <route id="NW" edges="N2J J2W"/>
            <route id="SE" edges="S2J J2E"/>
            <route id="SW" edges="S2J J2W"/>
            <route id="EN" edges="E2J J2N"/>
            <route id="ES" edges="E2J J2S"/>
            <route id="WN" edges="W2J J2N"/>
            <route id="WS" edges="W2J J2S"/>

            <!-- Main NS flows (peak) -->
            <flow id="flow_NS" type="car" route="NS" begin="0" end="{sim_end}"
                  vehsPerHour="{ns_each}" departLane="random" departSpeed="max"/>
            <flow id="flow_SN" type="car" route="SN" begin="0" end="{sim_end}"
                  vehsPerHour="{ns_each}" departLane="random" departSpeed="max"/>

            <!-- Main EW flows (peak) -->
            <flow id="flow_EW" type="car" route="EW" begin="0" end="{sim_end}"
                  vehsPerHour="{ew_each}" departLane="random" departSpeed="max"/>
            <flow id="flow_WE" type="car" route="WE" begin="0" end="{sim_end}"
                  vehsPerHour="{ew_each}" departLane="random" departSpeed="max"/>

            <!-- Turning flows (~15% of through volume) -->
            <flow id="flow_NE" type="car" route="NE" begin="0" end="{sim_end}" vehsPerHour="{ns_each//5}" departLane="random" departSpeed="max"/>
            <flow id="flow_NW" type="car" route="NW" begin="0" end="{sim_end}" vehsPerHour="{ns_each//10}" departLane="random" departSpeed="max"/>
            <flow id="flow_SE" type="car" route="SE" begin="0" end="{sim_end}" vehsPerHour="{ns_each//10}" departLane="random" departSpeed="max"/>
            <flow id="flow_SW" type="car" route="SW" begin="0" end="{sim_end}" vehsPerHour="{ns_each//5}" departLane="random" departSpeed="max"/>
            <flow id="flow_EN" type="car" route="EN" begin="0" end="{sim_end}" vehsPerHour="{ew_each//6}" departLane="random" departSpeed="max"/>
            <flow id="flow_ES" type="car" route="ES" begin="0" end="{sim_end}" vehsPerHour="{ew_each//10}" departLane="random" departSpeed="max"/>
            <flow id="flow_WN" type="car" route="WN" begin="0" end="{sim_end}" vehsPerHour="{ew_each//10}" departLane="random" departSpeed="max"/>
            <flow id="flow_WS" type="car" route="WS" begin="0" end="{sim_end}" vehsPerHour="{ew_each//6}" departLane="random" departSpeed="max"/>

        </routes>
        """)

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(content, encoding="utf-8")
    print(f"Routes written to {output}")


def main() -> None:
    """CLI entry point."""
    parser = argparse.ArgumentParser(
        description="Generate SUMO route file for NeuroTraffic-RL."
    )
    parser.add_argument("--output", default=str(_DEFAULT_OUTPUT), help="Output .rou.xml path")
    parser.add_argument("--ns-peak",     type=int, default=800, help="Peak NS demand (veh/hr)")
    parser.add_argument("--ew-peak",     type=int, default=600, help="Peak EW demand (veh/hr)")
    parser.add_argument("--ns-offpeak",  type=int, default=300, help="Off-peak NS demand (veh/hr)")
    parser.add_argument("--ew-offpeak",  type=int, default=200, help="Off-peak EW demand (veh/hr)")
    parser.add_argument("--sim-end",     type=int, default=3600, help="Simulation end (seconds)")
    args = parser.parse_args()

    generate_routes(
        output=Path(args.output),
        ns_peak=args.ns_peak,
        ew_peak=args.ew_peak,
        ns_offpeak=args.ns_offpeak,
        ew_offpeak=args.ew_offpeak,
        sim_end=args.sim_end,
    )


if __name__ == "__main__":
    main()
